openapi: 3.0.0
info:
  title: SAP Product Service
  description: API specification for SAP product integration
  version: 1.0.0

servers:
  - url: ${{OPENAPI_SERVER_URL}}/api
    description: The SAP product api server

paths:
  /products:
    get:
      operationId: listProducts
      summary: List all products
      description: Returns a list of products from SAP system
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: The unique identifier of the product
                        name:
                          type: string
                          description: The name of the product
                        description:
                          type: string
                          description: The detailed description of the product
                        price:
                          type: number
                          description: The price of the product
                        category:
                          type: string
                          description: The category of the product